<?php
/**
 * @file
 * Code for the AE Email Protest Target Contact Type feature.
 */

include_once 'campaignion_protest_target.features.inc';

/**
 * Implements hook_field_widget_info().
 */
function campaignion_protest_target_field_widget_info() {
  $fields['email_protest_target'] = array(
    'label'       => t('Email protest target'),
    'field types' => array('entityreference'),
    'behaviors'   => array(
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );

  return $fields;
}

/**
 * Implements hook_field_widget_form().
 */
function campaignion_protest_target_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $default_values = array(
    'first_name'    => NULL,
    'last_name'     => NULL,
    'email' => NULL,
  );

  if (isset($items[$delta]['target_id']) == TRUE) {
    $target_contact = entity_load('redhen_contact', array($items[$delta]['target_id']));
    if ($target_contact != FALSE) {
      $target_contact = array_shift($target_contact);
      $default_values = array(
        'first_name'    => $target_contact->first_name,
        'last_name'     => $target_contact->last_name,
        'email' => $target_contact->redhen_contact_email['und']['0']['value'],
      );
    }
  }

  $element['email_protest_target'] = array(
    '#type'  => 'fieldset',
  );

  $element['email_protest_target']['first_name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('First Name'),
    '#default_value' => $default_values['first_name'],
  );
  $element['email_protest_target']['last_name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Last Name'),
    '#default_value' => $default_values['last_name'],
  );
  $element['email_protest_target']['email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Email Address'),
    '#default_value' => $default_values['email'],
  );
  $element['#element_validate'] = array('campaignion_protest_target_validate');

  return $element;
}

/**
 * Field validation callback function referenced in campaignion_protest_target_field_widget_form
 */
function campaignion_protest_target_validate($element, &$form_state, $form) {

  $target = &$element['email_protest_target'];

  if (   empty($target['first_name']['#value'])    == FALSE
      || empty($target['last_name']['#value'])     == FALSE
      || empty($target['email']['#value']) == FALSE) {

    if (empty($target['first_name']['#value']) == TRUE) {
      form_error($target['first_name'], t('First name has to be a non empty string.'));
    }

    if (empty($target['last_name']['#value']) == TRUE) {
      form_error($target['last_name'], t('Last name has to be a non empty string.'));
    }

    if (empty($target['email']['#value']) == TRUE) {
      form_error($target['email'], t('The email address has to be a non empty string.'));
    }
    elseif (valid_email_address($target['email']['#value']) == FALSE) {
      form_error($target['email'], t('The email address you entered is not a valid email address.'));
    }

    $importer = new \Drupal\campaignion\CRM\Import\MappedImport();
    $source   = new \Drupal\campaignion\CRM\Import\Source\ArraySource($form_state['values']['field_protest_target']['und'][$element['#delta']]['email_protest_target']);
    $contact = $importer->import($source, 'email_protest_target');
    $form_state['values']['field_protest_target']['und'][$element['#delta']]['target_id'] = $contact ? $contact->contact_id : NULL;
  }
}

/* ********************************************************************************* */
/*                           webform component code                                  */
/* ********************************************************************************* */

/**
 * Implements hook_webform_component_info().
 */
function campaignion_protest_target_webform_component_info() {
  $components['protest_target'] = array(
    'label'       => t('Send your protest to'),
    'description' => t('Webform component to select a target person for an email protest.'),
    'features'    => array(
      'default_value' => TRUE,
      'required'      => TRUE,
    ),
    'file' => 'campaignion_protest_target.webform.inc',
  );

  return $components;
}

/**
 * Implements hook_form_builder_types().
 */
function campaignion_protest_target_form_builder_types() {

  require_once dirname(__FILE__) . '/campaignion_protest_target.webform.inc';
  require_once drupal_get_path('module', 'form_builder') . '/modules/webform/form_builder_webform.components.inc';

  $map = _form_builder_webform_property_map('protest_target');
  unset($map['properties']['default_value']);
  $fields['protest_target'] = array(
    'title'         => t('Email Protest Target Selector'),
    'palette_group' => 'advocacy_engine',
    'properties'    => array_keys($map['properties']),
    'default'       => array('#form_builder' => array('element_type' => 'protest_target')),
    'unique'        => TRUE,
  );

  $fields['protest_target']['default'] += _form_builder_webform_default('protest_target');

  return array('webform' => $fields);
}
