<?php

/**
 * @file
 * Code for the campaignion_petition feature.
 */

include_once 'campaignion_petition.features.inc';

/**
 * Implements hook_campaignion_action_info().
 */
function campaignion_petition_campaignion_action_info() {
  $types['petition'] = array(
    'wizard_class' => '\\Drupal\\campaignion_wizard\\PetitionWizard',
    'thank_you_page' => array(
      'type' => 'thank_you_page',
      'reference' => 'field_thank_you_pages',
    ),
    'recent_supporters' => array(
      'default_text' => t('!supporter_name just signed !action_title'),
    ),
    'template_node_uuid' => '2825470e-e582-414d-b01c-e6e71a028075',
  );
  return $types;
}

/**
 * Implements hook_form_FORM_ID_alter() for petition_node_form.
 */
function campaignion_petition_form_petition_node_form_alter(&$form, &$form_state, $form_id) {
  if (empty($form['title']['#default_value'])) {
    $form['title']['#default_value'] = t('Petition');
  }
}
