<?php

/**
 * @file
 * Code for the campaignion_flexible_form feature.
 */

include_once 'campaignion_flexible_form.features.inc';

/**
 * Implements hook_campaignion_action_info().
 */
function campaignion_flexible_form_campaignion_action_info() {
  $types['webform'] = array(
    'wizard_class' => '\\Drupal\\campaignion_wizard\\WebformWizard',
    'thank_you_page' => array(
      'type' => 'thank_you_page',
      'reference' => 'field_thank_you_pages',
    ),
    'recent_supporters' => array(
      'default_text' => t('!supporter_name just signed up at !action_title'),
    ),
    'template_node_uuid' => '93a8faff-aad2-401a-9817-f6f3b578b9bd',
  );
  return $types;
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_node_form.
 */
function campaignion_flexible_form_webform_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_thank_you_pages'] = FALSE;

  if (empty($form['title']['#default_value'])) {
    $form['title']['#default_value'] = t('Flexible form');
  }

  $form['title']['#weight'] = 210;
}
