<?php

/**
 * @file
 * Update hooks for the campaignion_protest_target_contact_type feature.
 */

/**
 * Implements hook_update_dependencies().
 */
function campaignion_protest_target_contact_type_update_dependencies() {
  $dependencies['campaignion_protest_target_contact_type'][1]['campaignion_protest_target'] = 2;
  return $dependencies;
}

/**
 * Delete contact type and contacts.
 */
function campaignion_protest_target_contact_type_update_1(){
  redhen_contact_type_load('email_protest_target')->delete(TRUE);
}
