<?php
/**
 * @file
 * Code for the AE Contact type feature.
 */

include_once 'campaignion_supporter.features.inc';

/**
 * Implements hook_entity_presave().
 */
function campaignion_supporter_entity_presave($entity, $type) {
  if ($type != 'redhen_contact' || $entity->type != 'contact') {
    return;
  }

  $wc = entity_metadata_wrapper('redhen_contact', $entity);
  $gender = $wc->field_gender->value();
  $salutation = $wc->field_salutation->value();
  $gmapping = array('f' => 'mrs', 'm' => 'mr');
  $smapping = array('mrs' => 'f', 'mr' => 'm');
  if (!$gender && $salutation && isset($smapping[$salutation])) {
    $wc->field_gender->set($smapping[$salutation]);
  }
  elseif (!$salutation && $gender && isset($gmapping[$gender])) {
    $wc->field_salutation->set($gmapping[$gender]);
  }
}

/**
 * Implements hook_campaignion_contact_info().
 */
function campaignion_supporter_campaignion_contact_type_info() {
  $types['contact'] = '\\Drupal\\campaignion_supporter\\Supporter';
  return $types;
}

/**
 * Implements hook_campaignion_action_contact_alter().
 */
function campaignion_supporter_campaignion_action_contact_alter($contact, $submission, $action_node) {
  if ($submission->is_draft) {
    return FALSE;
  }

  $changed = FALSE;
  $w = $contact->wrap();
  if (!$w->field_opt_in_phone->value()) {
    $components = $submission->webform->componentsByType('phone_number');
    foreach ($components as $cid => $component) {
      if (!empty($component['extra']['implies_optin'])) {
        $values = $submission->valuesByCid($cid);
        $value = reset($values);
        if ($value) {
          $w->field_opt_in_phone->set(TRUE);
          $changed = TRUE;
        }
      }
    }
  }

  return $changed;
}
