<?php
/**
 * @file
 * Code for the AE Contact type feature.
 */

include_once 'campaignion_supporter.features.inc';

use \Drupal\campaignion\ContactTypeManager;
use \Drupal\little_helpers\Webform\Submission;

/**
 * Implements hook_campaignion_action_taken().
 */
function campaignion_supporter_campaignion_action_taken($node, Submission $submissionObj) {
  $importer = ContactTypeManager::instance()->importer('campaignion_action_taken');
  $contact = $importer->findOrCreateContact($submissionObj);
  $changed = $importer->import($submissionObj, $contact);
  // Allow other modules to change the contact.
  foreach (module_implements('campaignion_supporter_contact_alter') as $module) {
    $function = $module . '_campaignion_supporter_contact_alter';
    $changed |= $function($contact, $submissionObj, $node);
  }
  if ($changed) {
    $contact->save();
  }
  return $contact;
}

/**
 * Implements hook_entity_presave().
 */
function campaignion_supporter_entity_presave($entity, $type) {
  if ($type != 'redhen_contact' || $entity->type != 'contact') {
    return;
  }

  $wc = entity_metadata_wrapper('redhen_contact', $entity);
  $gender = $wc->field_gender->value();
  $salutation = $wc->field_salutation->value();
  $gmapping = array('f' => 'mrs', 'm' => 'mr');
  $smapping = array('mrs' => 'f', 'mr' => 'm');
  if (!$gender && $salutation && isset($smapping[$salutation])) {
    $wc->field_gender->set($smapping[$salutation]);
  }
  elseif (!$salutation && $gender && isset($gmapping[$gender])) {
    $wc->field_salutation->set($gmapping[$gender]);
  }
}

/**
 * Implements hook_campaignion_contact_info().
 */
function campaignion_supporter_campaignion_contact_type_info() {
  $types['contact'] = '\\Drupal\\campaignion_supporter\\Supporter';
  return $types;
}
