<?php
/**
 * @file
 * Code for the AE Contact type feature.
 */

include_once 'campaignion_supporter.features.inc';

/**
 * Implements hook_entity_presave().
 */
function campaignion_supporter_entity_presave($entity, $type) {
  if ($type != 'redhen_contact' || $entity->type != 'contact') {
    return;
  }

  $wc = entity_metadata_wrapper('redhen_contact', $entity);
  $gender = $wc->field_gender->value();
  $salutation = $wc->field_salutation->value();
  $gmapping = array('f' => 'mrs', 'm' => 'mr');
  $smapping = array('mrs' => 'f', 'mr' => 'm');
  if (!$gender && $salutation && isset($smapping[$salutation])) {
    $wc->field_gender->set($smapping[$salutation]);
  }
  elseif (!$salutation && $gender && isset($gmapping[$gender])) {
    $wc->field_salutation->set($gmapping[$gender]);
  }
}

/**
 * Implements hook_campaignion_contact_info().
 */
function campaignion_supporter_campaignion_contact_type_info() {
  $types['contact'] = '\\Drupal\\campaignion_supporter\\Supporter';
  return $types;
}
