<?php

/**
 * @file
 * Code for the campaignion_conf feature.
 */

include_once 'campaignion_conf.features.inc';

function campaignion_conf_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'file_default_displays_alter') {
    unset($implementations['image']);
    unset($implementations['media_youtube']);
  }
  // Ignore diff & comment variables for node-types.
  if ($hook == 'features_pipe_node_alter') {
    unset($implementations['diff']);
    // Ensure our hook implementation is called late.
    $group = $implementations['campaignion_conf'];
    unset($implementations['campaignion_conf']);
    $implementations['campaignion_conf'] = $group;
  }
}

/**
 * Implements hook_block_info_alter()
 * 
 * @todo maybe this is a bad idea and we really should use fe_block
 */
function campaignion_conf_block_info_alter(&$blocks) {
  $blocks['system']['navigation']['status'] = 0;
  $blocks['system']['management']['status'] = 0;
  $blocks['user']['login']['status'] = 0;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_webform_admin_settings_alter().
 */
 function campaignion_conf_form_webform_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['email']['webform_default_from_address']['#value'] = variable_get('site_mail', ini_get('sendmail_from'));
  $form['email']['webform_default_from_address']['#disabled'] = TRUE;
}

/**
 * Implements hook_features_pipe_COMPONENT_alter() for node.
 */
function campaignion_conf_features_pipe_node_alter(&$pipe, $data, $export) {
  $pipe['variable'] = array_filter($pipe['variable'], function ($name) {
    if (substr($name, 0, 8) == 'comment_') {
      return FALSE;
    }
    return TRUE;
  });
}
