<?php

/**
 * @file
 * Implements all needed hooks and functions.
 */

/**
 * Implements hook_entity_view().
 */
function campaignion_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type === 'field_collection_item') {
    $content = field_get_items($type, $entity, 'campaignion_overlay_content');
    $intro = field_get_items($type, $entity, 'campaignion_overlay_introduction');
    $node = node_load($content[0]['target_id']);
    $form = drupal_get_form('webform_client_form_' . $node->nid, $node, []);

    $entity->content['campaignion_overlay_introduction'] = [
      '#markup' => '<em>' . $intro[0]['safe_value'] . '</em>',
    ];
    $entity->content['campaignion_overlay_content'] = [
      '#markup' => drupal_render($form),
      '#weight' => 99,
    ];

    $enabled = field_get_items($type, $entity, 'campaignion_overlay_enabled');
    $enabled = $enabled[0]['value'] === '1';
    drupal_add_library('system', 'ui.dialog');
    drupal_add_js(['campaignion_overlay' => ['overlay_enabled' => $enabled]], 'setting');
  }
}

/**
 * Prepares variables for field templates.
 *
 * Default template: field.tpl.php.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #field_name.
 *   - classes_array: An associative array containing CSS classes of the field.
 *     Properties used: #classes_array.
 */
function campaignion_overlay_preprocess_field(array &$variables) {
  $field_name = $variables['element']['#field_name'];

  if ($field_name === 'campaignion_overlay_options') {
    $variables['classes_array'][] = 'campaignion-overlay-options';
  }
  if ($field_name === 'campaignion_overlay_content') {
    $variables['classes_array'][] = 'campaignion-overlay-content';
  }
  if ($field_name === 'campaignion_overlay_introduction') {
    $variables['classes_array'][] = 'campaignion-overlay-introduction';
  }
}
