<?php
/**
 * @file
 * Code for the donation content-type.
 */

use Drupal\little_helpers\Webform\Webform;

include_once 'campaignion_donation_type.features.inc';

/**
 * Implements hook_block_info_alter().
 *
 * Hide titles of specified blocks
 */
function campaignion_donation_type_block_view_alter(&$data, $block) {
  $hide_title_fields = array('field_main_image');

  foreach($hide_title_fields as $field_name) {
    if(isset($block->delta) && $block->delta === $field_name) {
      $data['subject'] = '';
    }
  }
}

/**
 * Implements hook_campaignion_action_info().
 */
function campaignion_donation_type_campaignion_action_info() {
  $type['donation'] = array(
    'wizard_class' => '\\Drupal\\campaignion_wizard\\DonationWizard',
    'thank_you_page' => array(
      'type' => 'thank_you_page',
      'reference' => 'field_thank_you_pages',
    ),
    'recent_supporters' => array(
      'default_text' => t('!supporter_name just donated at !action_title'),
    ),
    'template_node_uuid' => '6eb388a0-88e5-4272-bb6e-0bd8e8da595e',
    'donation' => TRUE,
  );
  return $type;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_donation_node_form_alter().
 */
function campaignion_donation_type_form_donation_node_form_alter(&$form, &$form_state, $form_id) {
  if (empty($form['title']['#default_value'])) {
    $form['title']['#default_value'] = t('Donation');
  }
  $form['title']['#weight'] = 210;
}

/**
 * Implements hook_node_prepare().
 */
function campaignion_donation_type_node_prepare($node) {
  if ($node->type == 'donation' && empty($node->webform['submit_text'])) {
    $node->webform['submit_text'] = t('Donate now!');
  }
}
